### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by emako** [Irrational-Encoding-Wizardry/vapoursynth-autocrop#1]
It cant work, cause of output is the varying size clip.

**Comment by kageru** [comment]
Vapoursynth does indeed support varying frame size clips, but that data cannot properly be read by any other program, so you have to either add new borders with FrameEval (which is pointless if you’ve just removed them, but hey, you’re the boss) or resize to a constant resolution. The latter will obviously skew the aspect ratio, but for the given use case—that being old DVDs with varying border sizes—this error is negligible.

**Comment by stuxcrystal** [comment]
While we're at it.

Naming an issue `BUG` is probably the worst way of getting your issue resolved:

1. It is considered rude to write in capslock
2. It does not give an idea what kind of issue you have on the issue-list
3. Your report has not nearly enough information on your Environment.

Therefore, even if this were an actual bug, the report would be utterly useless.
